# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='El nombre del proyecto', max_length=128, unique=True, verbose_name='Nombre del proyecto')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('creation_date', models.DateField(blank=True, editable=False, null=True)),
                ('update_date', models.DateField(blank=True, editable=False, null=True)),
                ('summary', models.TextField(blank=True, help_text='Una resumen corto del proyecto para cabeceras y vistas.', verbose_name='Resumen')),
                ('start_date', models.DateField(blank=True, editable=False, help_text='Fecha aproximada de comienzo del proyecto.', null=True, verbose_name='Fecha de comienzo')),
                ('end_date', models.DateField(blank=True, editable=False, help_text='Fecha aproximada de finalización del proyecto.', null=True, verbose_name='Fecha de finalización')),
            ],
        ),
    ]
