# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fecha aproximada de finalización del proyecto.', null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='related_entity',
            field=models.ManyToManyField(blank=True, help_text='Especifica aquí los clientes del Proyecto.', to='models.RelatedEntity', verbose_name='Entidades relacionadas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, help_text='Fecha aproximada de comienzo del proyecto.', null=True, verbose_name='Fecha de comienzo'),
        ),
        migrations.AlterField(
            model_name='relatedentity',
            name='category',
            field=models.URLField(choices=[('CL', 'Cliente'), ('CO', 'Colaborador'), ('FI', 'Financiador')], help_text='Especifica la relación de la entidad con el proyecto', verbose_name='Categoría'),
        ),
    ]
