# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20171027_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='relatedentity',
            options={'verbose_name': 'Entidad relacionada', 'verbose_name_plural': 'Entidades relacionadas'},
        ),
        migrations.AlterModelOptions(
            name='techtaxonomy',
            options={'verbose_name': 'Tecnología', 'verbose_name_plural': 'Tecnologías'},
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
