# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 14:05
from __future__ import unicode_literals

import apps.models.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(help_text='Sube una imagen representativa haciendo click en la imagen inferior.La imagen ha de tener ancho mínimo de 300 píxeles y máximo de 1920, y altura mínima de 300 píxeles y máxima de 1280. Formatos permitidos: PNG, JPG, JPEG.', upload_to='', validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Archivo')),
                ('alt_text', models.CharField(help_text='Texto que describe la imagen para screen readers ', max_length=128, verbose_name='Texto alternativo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Project')),
            ],
        ),
    ]
