# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Texto que describe la imagen para screen readers ', max_length=128, verbose_name='Texto alternativo'),
        ),
    ]
