# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20171025_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(help_text='Sube una imagen representativa haciendo click en la imagen inferior.La imagen ha de tener ancho mínimo de 300 píxeles y máximo de 1920, y altura mínima de 300 píxeles y máxima de 1280. Formatos permitidos: PNG, JPG, JPEG.', upload_to='', verbose_name='Archivo'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
