# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_project_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedentity',
            name='category',
            field=models.CharField(choices=[('CL', 'Cliente'), ('CO', 'Colaborador'), ('FI', 'Financiador')], help_text='Especifica la relación de la entidad con el proyecto', max_length=128, verbose_name='Categoría'),
        ),
    ]
