# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20171027_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='related_entity',
        ),
        migrations.RemoveField(
            model_name='relatedentity',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='clients', to='models.RelatedEntity', verbose_name='Clientes'),
        ),
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to='models.RelatedEntity', verbose_name='Colaborador@s'),
        ),
    ]
