# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 10:30
from __future__ import unicode_literals

import apps.models.utils
import apps.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20171026_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del cliente', max_length=128, verbose_name='Nombre del client')),
                ('link', models.URLField(help_text='Enlace opcional para obtener más info sobre el cliente', verbose_name='Enlace a un site relacionado')),
            ],
        ),
        migrations.CreateModel(
            name='TechTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la tecnología', max_length=128, verbose_name='Tecnología')),
                ('description', models.TextField(blank=True, help_text='Una resumen corto de la tecnología.', verbose_name='Resumen')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(help_text='Texto que describe la imagen para screen readers ', max_length=128, verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(help_text='Sube una imagen representativa haciendo click en la imagen inferior.La imagen ha de tener ancho mínimo de 300 píxeles y máximo de 1920, y altura mínima de 300 píxeles y máxima de 1280. Formatos permitidos: PNG, JPG, JPEG.', upload_to=apps.models.utils.RenameProjectImage(), validators=[apps.models.validators.ImageSizeValidator({'max_height': 1280, 'max_width': 1920, 'min_height': 300, 'min_width': 600}), apps.models.validators.ImageTypeValidator(['jpeg', 'png'])], verbose_name='Archivo'),
        ),
    ]
