# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20171027_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='credits',
            field=models.CharField(blank=True, help_text='Especifica los créditos de la imagen en caso necesario', max_length=128, verbose_name='Créditos'),
        ),
    ]
