# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20171031_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre del sitio')),
                ('link', models.URLField(verbose_name='Enlace al site')),
                ('summary', models.TextField(blank=True, help_text='Una resumen corto opcional del contenido.', verbose_name='Resumen')),
            ],
            options={
                'verbose_name_plural': 'Enlaces',
                'verbose_name': 'Enlace',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(blank=True, help_text='Especifica aquí enlaces para ampliar información del proyecto.', to='models.Link', verbose_name='Enlaces'),
        ),
    ]
